version: "3.6"

services:
  app:
    image: node:gallium-alpine
    command: npm run dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
